### ISSUE TITLE
Hijack pose2sim trace file maker

### ISSUE THREAD

**Issue by aaroncherian** [aaroncherian/freemocap_validation#13]
- convert data into a pandas dataframe that can be potentially taken in by pose2sim methods to convert into a .trc file?
- create a dataframe from freemocap data
- make dataframes for body, right hand, left hand and face (separately)
- check mediapipe documentation for names for body parts

**Comment by jonmatthis** [comment]
kinda done, some weird buggos

next step is probably to make our own method that serves our needs better
